dashboard/config/routes.rb
Dashboard::Engine.routes.draw do
  scope ':environment_id', as: :environment do
    resource :dashboard, controller: :dashboard, only: :show do
      resource :sdp, controller: :service_delivery_plans
    end
  end
end

dashboard/app/models/dashboard/service_delivery_plan.rb
module Dashboard
  class ServiceDeliveryPlan < ActiveRecord::Base
    belongs_to :environment
    has_attached_file :file
    validates_attachment_file_name :file, matches: [/xlsm?\z/]
    validates :environment, :file, presence: true
    validates :environment_id, uniqueness: true

    def self.for_environment env
      find_by environment_id: env
    end
  end
end

dashboard/app/controllers/dashboard/application_controller.rb
module Dashboard
  class ApplicationController < ::ApplicationController
    self.component_name = :dashboard
    before_filter :require_enabled_component!
  end
end

dashboard/app/controllers/dashboard/dashboard_controller.rb
module Dashboard
  class DashboardController < ApplicationController
    inherit_resources
    belongs_to :environment, finder: :find_by_slug!
    def show
      @report = Dsars::Report.where(report_type: '5266', dro_number: parent.dr_number, scope: 'Consolidated').order{report_number.desc}.first
      @sdp = ServiceDeliveryPlan.for_environment parent
    end

    protected

    def add_breadcrumbs
      breadcrumb "Dashboard"
    end
  end
end

dashboard/app/controllers/dashboard/service_delivery_plans_controller.rb
module Dashboard
  class ServiceDeliveryPlansController < ApplicationController
    inherit_resources
    defaults singleton: true, route_instance_name: :dashboard_sdp, route_prefix: nil
    belongs_to :environment, finder: :find_by_slug!
    actions :new, :edit, :update, :create

    def update
      update! { environment_dashboard_path parent }
    end

    protected

    def add_breadcrumbs
      super
      breadcrumb "Dashboard", environment_dashboard_path(parent)
      breadcrumb "SDP"
    end

    def resource
      @service_delivery_plan ||= ServiceDeliveryPlan.for_environment(parent)
    end

    def build_resource
      @service_delivery_plan ||= begin
        plan = ServiceDeliveryPlan.new(*resource_params)
        plan.environment = parent
        plan
      end
    end

    def permitted_params
      params.permit(:service_delivery_plan => [:approved_budget, :file])
    end
  end
end

dashboard/app/helpers/dashboard/application_helper.rb
module Dashboard
  module ApplicationHelper
  end
end

dashboard/app/helpers/dashboard/dashboard_helper.rb
module Dashboard
  module DashboardHelper
    def incident_name
      @report.incident_name
    end

    def lines
      @lines ||= @report.lines.group_by(&:line_number)
    end

    def period_value line_number, default=nil
      line = lines[line_number].first
      line && line.period || default
    end

    def total_value line_number, default=nil
      line = lines[line_number].first
      line && line.total || default
    end

    def period_indirect
      (period_value(141) || 0) - (period_value(92) || 0) - (period_value(97) || 0)
    end

    def total_indirect
      (total_value(141) || 0) - (total_value(92) || 0) - (total_value(97) || 0)
    end

    def chart_link line, text
      link_to (text || ""), dsars.report_chart_path(parent, @report.report_number, line)
    end

    def assigned_staff_by_gap
      @staff ||= current_environment.assigned_staff.to_a.group_by{|as| as.group}.merge(current_environment.assigned_staff.to_a.group_by{|as| "#{as.group}/#{as.activity}"})
      @staff.default = []
      @staff
    end

    def efficiency_model
      {
        "Shelter Overnight Stays" => {line: 17, default_weight: 10, gap: 'MC', cost_basis: [124], noun: 'stays'},
        "Health Services Contacts" => {line: 75, default_weight: 40, gap: 'CLS/HS', cost_basis: [99,113], noun: 'contacts'},
        "Mental Health Contacts" => {line: 79, default_weight: 40, gap: 'CLS/DMH', cost_basis: [100, 114], noun: 'contacts'},
        "Cases Open" => {line: 60, default_weight: 5, gap: 'CLS/CC', cost_basis: [98, 112], noun: 'open cases'},
        "Individual Financial Assistance" => {line: 92, default_weight: 0.1, gap: 'CLS/CC', cost_basis: [98, 112], noun: 'dollars provided'}
      }
    end

    def overhead
      @overhead ||= [132, 133, 103, 117, 137, 138, 139, 140].map{|line| total_value(line, 0) }.sum
    end

    def total_weight
      efficiency_model.map{|name, model|
        weight = weight(name, model)
        total_value(model[:line], 0) * weight
      }.sum
    end

    def weight name, model
      param = name.to_param
      (params.key?(param) ? params[param].to_f : model[:default_weight])
    end
  end
end

dashboard/app/views/dashboard/dashboard/index.html.haml
.row
  .col-md-12
    %h1 DR #{@report.dro_number} Dashboard
.row
  .col-md-12
    %table.table.table-bordered.table-striped
      %tr
        %th Incident Name
        %td=incident_name
      /%tr
      /  %td DSARS Incident #
      /  %td=@report.incident_number
      /%tr
      /  %td CAS Incident #
      /  %td
      %tr
        %th Incident Type
        %td
      %tr
        %th Incident Date
        %td
      %tr
        %th Reporting Frequency
        %td
          Daily
          \-
          =@report.cob_date
      %tr
        %th Job Director
        %td
      %tr
        %th Service Delivery Plan
        %td
.row
  .col-md-12
    %h3 Casework
    %table.table.table-bordered.table-striped
      %tr
        %th
        %th Estimated Cases
        %th Contacts
        %th Cases Open (current)
        %th Cases Closed (total)
      %tr
        %th Client Casework
        %td=chart_link 55, total_value(55)
        %td
        %td=chart_link 60, period_value(60)
        %td=[period_value(58),period_value(59)].compact.sum
      %tr
        %th Health Services
        %td
        %td=chart_link 75, total_value( 75)
        %td=chart_link 77, period_value( 77)
        %td=chart_link 78, total_value( 78)
      %tr
        %th Mental Health
        %td
        %td=chart_link 79, total_value(79)
        %td=chart_link 81, period_value(81)
        %td=chart_link 82, total_value(82)
.row
  .col-md-6
    %h3 Staffing
    %table.table.table-bordered.table-striped
      %tr
        %th(rowspan=2)
        %th(colspan=2) Local
        %th(colspan=2) Deployed
      %tr
        %th Period
        %th Total
        %th Period
        %th Total
      %tr
        %th Volunteer
        %td=chart_link 38, period_value( 38)
        %td=chart_link 38, total_value( 38)
        %td=chart_link 41, period_value( 41)
        %td=chart_link 41, total_value( 41)
      %tr
        %th Employees
        %td=chart_link 39, period_value( 39)
        %td=chart_link 39, total_value( 39)
        %td=chart_link 42, period_value( 42)
        %td=chart_link 42, total_value( 42)
      %tr
        %th Overall
        %td=chart_link 40, period_value( 40)
        %td=chart_link 40, total_value( 40)
        %td=chart_link 44, period_value( 44)
        %td=chart_link 44, total_value( 44)
  .col-md-6
    %h3 Mass Care
    %table.table.table-bordered.table-striped
      %tr
        %th
        %th Period
        %th Total
      %tr
        %th Shelters
        %td=chart_link 1, period_value(1)
        %td=chart_link 1, total_value( 1)
      %tr
        %th Shelter Registrations
        %td=chart_link 16, period_value(16)
        %td=chart_link 16, total_value( 16)
      %tr
        %th Shelter Stays
        %td=chart_link 17, period_value(17)
        %td=chart_link 17, total_value( 17)
      %tr
        %th Meals Served
        %td=chart_link 18, period_value(18)
        %td=chart_link 18, total_value( 18)
.row
  .col-md-12
    %h3 Expenditures
    %table.table.table-bordered.table-striped
      %tr
        %th Class
        %th Description
        %th 5266 Line
        %th Period
        %th Total
      %tr
        %th Class 1
        %th Mass Care
        %td 97
        %td=chart_link 97, number_to_currency( period_value(97), precision: 0)
        %td=chart_link 97, number_to_currency( total_value( 97), precision: 0)
      %tr
        %th Class 2
        %th Personal Items
        %td 83
        %td=chart_link 83, number_to_currency( period_value(83), precision: 0)
        %td=chart_link 83, number_to_currency( total_value( 83), precision: 0)
      %tr
        %th Class 3
        %th Hotel, Rental Assistance
        %td 84
        %td=chart_link 84, number_to_currency( period_value(84), precision: 0)
        %td=chart_link 84, number_to_currency( total_value( 84), precision: 0)
      %tr 
        %th Class 4
        %th Beds, Bedding, Storage
        %td 85
        %td=chart_link 85, number_to_currency( period_value(85), precision: 0)
        %td=chart_link 85, number_to_currency( total_value( 85), precision: 0)
      %tr
        %th Class 5
        %th Health Needs
        %td 88+89
        %td=number_to_currency( [period_value(88),period_value(89)].compact.sum, precision: 0)
        %td=number_to_currency( [total_value( 88),total_value( 89)].compact.sum, precision: 0)
      %tr
        %th
        %th Total Direct Services
        %td 92+97
        %td=number_to_currency( [period_value(92),period_value(97)].compact.sum, precision: 0)
        %td=number_to_currency( [total_value( 92),total_value( 97)].compact.sum, precision: 0)
      %tr
        %th
        %th Total Indirect Expenditures
        %td 141-92-97
        %td=number_to_currency( period_indirect, precision: 0)
        %td=number_to_currency( total_indirect, precision: 0)
      %tr
        %th
        %th Operation Total Commitments
        %td 141
        %td=chart_link 141, number_to_currency( period_value(141), precision: 0)
        %td=chart_link 141, number_to_currency( total_value( 141), precision: 0)
      %tr
        %th
        %th Operation Approved Budget
        %td(colspan=2)
        %td $?

dashboard/app/views/dashboard/dashboard/show.html.haml
.row
  .col-md-12
    %h1 DR #{@report.dro_number} Dashboard
.row
  .col-md-12
    %table.table.table-bordered.table-striped
      %tr
        %th Incident Name
        %td=incident_name
      /%tr
      /  %td DSARS Incident #
      /  %td=@report.incident_number
      /%tr
      /  %td CAS Incident #
      /  %td
      %tr
        %th Incident Type
        %td
      %tr
        %th Incident Date
        %td
      %tr
        %th Reporting Frequency
        %td
          Daily
          \-
          =@report.cob_date
      %tr
        %th Job Director
        %td
      %tr
        %th Service Delivery Plan
        %td
          - if @sdp
            =link_to 'Download', @sdp.file.expiring_url
            (Updated #{@sdp.updated_at} | 
            =link_to 'Upload New', edit_environment_dashboard_sdp_path(parent)
            )
          - else
            =link_to 'Upload', new_environment_dashboard_sdp_path(parent)
.row
  .col-md-12
    %h3 Casework
    %table.table.table-bordered.table-striped
      %tr
        %th
        %th Estimated Cases
        %th Contacts
        %th Cases Open (current)
        %th Cases Closed (total)
      %tr
        %th Client Casework
        %td=chart_link 55, total_value(55)
        %td
        %td=chart_link 60, period_value(60)
        %td=[period_value(58),period_value(59)].compact.sum
      %tr
        %th Health Services
        %td
        %td=chart_link 75, total_value( 75)
        %td=chart_link 77, period_value( 77)
        %td=chart_link 78, total_value( 78)
      %tr
        %th Mental Health
        %td
        %td=chart_link 79, total_value(79)
        %td=chart_link 81, period_value(81)
        %td=chart_link 82, total_value(82)
.row
  .col-md-6
    %h3 Staffing
    %table.table.table-bordered.table-striped
      %tr
        %th(rowspan=2)
        %th(colspan=2) Local
        %th(colspan=2) Deployed
      %tr
        %th Period
        %th Total
        %th Period
        %th Total
      %tr
        %th Volunteer
        %td=chart_link 38, period_value( 38)
        %td=chart_link 38, total_value( 38)
        %td=chart_link 41, period_value( 41)
        %td=chart_link 41, total_value( 41)
      %tr
        %th Employees
        %td=chart_link 39, period_value( 39)
        %td=chart_link 39, total_value( 39)
        %td=chart_link 42, period_value( 42)
        %td=chart_link 42, total_value( 42)
      %tr
        %th Overall
        %td=chart_link 40, period_value( 40)
        %td=chart_link 40, total_value( 40)
        %td=chart_link 44, period_value( 44)
        %td=chart_link 44, total_value( 44)
    %h3 Mass Care
    %table.table.table-bordered.table-striped
      %tr
        %th
        %th Period
        %th Total
      %tr
        %th Shelters
        %td=chart_link 1, period_value(1)
        %td=chart_link 1, total_value( 1)
      %tr
        %th Shelter Registrations
        %td=chart_link 16, period_value(16)
        %td=chart_link 16, total_value( 16)
      %tr
        %th Shelter Stays
        %td=chart_link 17, period_value(17)
        %td=chart_link 17, total_value( 17)
      %tr
        %th Meals Served
        %td=chart_link 18, period_value(18)
        %td=chart_link 18, total_value( 18)
  .col-md-6
    %h3 By GAP
    %table.table.table-bordered.table-striped
      %tr
        %th Group
        %th Count
      - ['OM', 'CLS/CC', 'CLS/HS', 'CLS/DMH', 'MC', 'LOG', 'ER', 'DST', 'IP', 'SS'].each do |group|
        %tr
          %th=group
          %td=assigned_staff_by_gap[group].count
      %tr
        %th Total (current)
        %td=current_environment.assigned_staff.count
-if current_ability.role? Roles::Dsars::FINANCIALS
  .row
    .col-md-12
      %h3 Expenditures
      %table.table.table-bordered.table-striped
        %tr
          %th Class
          %th Description
          %th 5266 Line
          %th Period
          %th Total
        %tr
          %th Class 1
          %th Mass Care
          %td 97
          %td=chart_link 97, number_to_currency( period_value(97), precision: 0)
          %td=chart_link 97, number_to_currency( total_value( 97), precision: 0)
        %tr
          %th Class 2
          %th Personal Items
          %td 83
          %td=chart_link 83, number_to_currency( period_value(83), precision: 0)
          %td=chart_link 83, number_to_currency( total_value( 83), precision: 0)
        %tr
          %th Class 3
          %th Hotel, Rental Assistance
          %td 84
          %td=chart_link 84, number_to_currency( period_value(84), precision: 0)
          %td=chart_link 84, number_to_currency( total_value( 84), precision: 0)
        %tr 
          %th Class 4
          %th Beds, Bedding, Storage
          %td 85
          %td=chart_link 85, number_to_currency( period_value(85), precision: 0)
          %td=chart_link 85, number_to_currency( total_value( 85), precision: 0)
        %tr
          %th Class 5
          %th Health Needs
          %td 88+89
          %td=number_to_currency( [period_value(88),period_value(89)].compact.sum, precision: 0)
          %td=number_to_currency( [total_value( 88),total_value( 89)].compact.sum, precision: 0)
        %tr
          %th
          %th Total Direct Services
          %td 92+97
          %td=number_to_currency( [period_value(92),period_value(97)].compact.sum, precision: 0)
          %td=number_to_currency( [total_value( 92),total_value( 97)].compact.sum, precision: 0)
        %tr
          %th
          %th Total Indirect Expenditures
          %td 141-92-97
          %td=number_to_currency( period_indirect, precision: 0)
          %td=number_to_currency( total_indirect, precision: 0)
        %tr
          %th
          %th Operation Total Commitments
          %td 141
          %td=chart_link 141, number_to_currency( period_value(141), precision: 0)
          %td=chart_link 141, number_to_currency( total_value( 141), precision: 0)
        %tr
          %th
          %th Operation Approved Budget
          %td(colspan=2)
          %td 
            -if @sdp
              =number_to_currency @sdp.approved_budget, precision: 0
            -else
              No SDP On File
  .row
    .col-sm-12
      %h3 Service Delivery Efficiency
      =form_tag '', method: :get do
        %table.table.table-bordered.table-striped
          %tr
            %th Metric
            %th Period
            %th Total
            %th $ Weight
            %th 
              $ Efficiency
              %br
              %small Indirect Dollars per Service
            %th
              Current Staff Efficiency
              %br
              %small Services per Period Staff
          - efficiency_model.each do |name, model|
            - line = model[:line]
            - param = name.to_param
            - weight = weight(name, model)
            - this_weight = weight * total_value(model[:line], 0)
            - this_total_val = total_value(line)
            %tr
              %th
                =name
              %td=period_value(line)
              %td=total_value(line)
              %td
                =text_field_tag param, weight, style: "width: 4em", class: 'form-control input-sm'
              - apportioned = (overhead * (this_weight.to_f / total_weight.to_f)) + model[:cost_basis].map{|l| total_value(l, 0)}.sum
              - eff = apportioned / (this_total_val || 0.0)
              %td=number_to_currency eff
              %td
                =number_with_precision(period_value(model[:line], 0).to_f / assigned_staff_by_gap[model[:gap]].count, precision: 2)
                %small #{model[:noun]} per staff in #{model[:gap]}
          %tr
            %td(colspan="3")
            %td=submit_tag 'Update', class: 'btn btn-default btn-sm'
            %td(colspan="2")