dsars/config/routes.rb
Dsars::Engine.routes.draw do
  scope ':environment_id/dsars' do
    resource :input, only: :show do
      post :input
    end
    resources :reports, only: [:index, :show] do
      resources :charts, only: :show
      resource :dosr, only: :show, controller: 'dosr'
    end
  end
end

dsars/app/models/dsars/dosr_config.rb
module Dsars
  class DosrConfig < ActiveRecord::Base
    belongs_to :environment

    def self.for_environment(env)
      not_exists = self.where{environment_id == env}.exists.not
      where{(environment_id == nil) | ((environment_id == nil) & not_exists)}
    end
  end
end

dsars/app/models/dsars/dosr_line.rb
module Dsars
  class DosrLine < ActiveRecord::Base
    self.table_name = "dsars_dosr_history"
    belongs_to :environment
    belongs_to :territory

    def readonly?
      true
    end
  end
end

dsars/app/models/dsars/line5266_description.rb
module Dsars
  class Line5266Description < ActiveRecord::Base
  end
end

dsars/app/models/dsars/line_description.rb
module Dsars
  class LineDescription < ActiveRecord::Base
  end
end

dsars/app/models/dsars/report.rb
module Dsars
  class Report < ActiveRecord::Base
    has_many :lines, class_name: 'ReportLine'
    has_one :dda, class_name: 'ReportDDA'

    def self.consolidated
      where(scope: 'Consolidated')
    end

    def self.form5266
      where(report_type: '5266')
    end
  end
end

dsars/app/models/dsars/report_dda.rb
module Dsars
  class ReportDDA < ActiveRecord::Base
  end
end

dsars/app/models/dsars/report_line.rb
module Dsars
  class ReportLine < ActiveRecord::Base
    belongs_to :report
  end
end

dsars/app/models/dsars/territory_config.rb
module Dsars
  class TerritoryConfig < ActiveRecord::Base
    belongs_to :incident
  end
end

dsars/app/controllers/dsars/application_controller.rb
module Dsars
  class ApplicationController < ::ApplicationController
    self.component_name = :dsars
    before_filter :require_enabled_component!

    protected

    def add_breadcrumbs
      breadcrumb "DSARS", reports_path(current_environment)
    end
  end
end

dsars/app/controllers/dsars/charts_controller.rb
module Dsars
  class ChartsController < ApplicationController
    inherit_resources
    belongs_to :environment, finder: :find_by_slug

    class LineInfo
      attr_reader :parent_report, :line_description, :lines
      def initialize(parent_report, line_description)
        @parent_report = parent_report
        @line_description = line_description
        @lines = ReportLine.joins{report}.where{(line_number == line_description.line_number) &
                                              (report.incident_number == parent_report.incident_number) &
                                              (report.scope == parent_report.scope) &
                                              (report.unit_id == parent_report.unit_id) &
                                              (report.county_id == parent_report.county_id)
                                              }.order{report.report_number}.includes{report}.to_a
      end

      def series_data col
        vals = @lines.map do |line|
          date = to_js_date(line.report.cob_date)
          val = line[col].to_json
          "[#{date}, #{val}]"
        end.compact

        "[#{vals.join ','}]"
      end

      def to_js_date(d)
        "Date.UTC(#{d.year}, #{d.month-1}, #{d.day})"
      end

      def chart_title
        "5266 Report #{parent_report.cob_date} - #{line_description.try :name}"
      end
    end

    def show
      @incident = params[:incident_id]

      @report = end_of_association_chain.first

      @line_numbers = params[:id].split ','
      @lines = @line_numbers.map do |line_no|
        line_description = LineDescription.where{(report_version == my{@report.report_version}) & (line_number == my{line_no})}.first
      
        if line_description.format == 'currency'
          authorize! Roles::Dsars::FINANCIALS
        end

        LineInfo.new @report, line_description
      end

      breadcrumb "Report #{@report.report_number}", report_path(parent, @report.report_number)
      breadcrumb @lines.first.line_description.name
    end

    def end_of_association_chain
      Report.where{(report_type == '5266')}.where{dro_number == my{parent.dr_number}}.consolidated
    end


    private

    helper_method :chart_title

  end
end

dsars/app/controllers/dsars/dosr_controller.rb
module Dsars
  class DosrController < ApplicationController
    inherit_resources
    helper ReportsHelper
    def show
      @environment = Environment.find_by_slug! params[:environment_id]
      report_num = params[:report_id]
      @report = Report.form5266.consolidated.where{(report_number==report_num) & (incident_number==my{@environment.dsars_incident_number})}.first
      @lines = DosrLine.where{(environment_id == my{@environment}) & (report_number==report_num) & ((period != nil) | (total != nil))}.includes{territory}.order{dosr_line_number}
      @lines.sort_by!{|l| [l.territory.ordinal, l.dosr_line_number]}
      @lines_by_territory = @lines.group_by(&:territory)
      line_numbers = @lines.map(&:dosr_line_number).uniq
      @configs = DosrConfig.for_environment(@environment).where{dosr_line_number.in line_numbers}.order{dosr_line_number}
    end

    protected

    def match_territory  report
      @scopes.detect do |scope|
        case scope.scope_type
        when 'consolidated' then report.scope == 'Consolidated'
        when 'chapter' then report.scope == 'Chapter' && report.unit_id == scope.unit_code
        when 'county' then report.scope == 'County' && report.county_id == scope.unit_code
        else false
        end
      end.try(:territory)
    end

    def add_breadcrumbs
      super
      breadcrumb "DOSR"
    end
  end
end

dsars/app/controllers/dsars/inputs_controller.rb
module Dsars
  class InputsController < ApplicationController
    include ActionController::Live
    inherit_resources
    belongs_to :environment, finder: :find_by_slug

    def show
      authorize! Roles::Dsars::IMPORT
      @since_date = 1.day.ago.to_date
      @dr_number = parent.dr_number
    end

    def input
      authorize! Roles::Dsars::IMPORT
      incident_number = parent.dsars_incident_number
      since = params[:data_since].present? && Date.parse(params[:data_since])
      consolidated_only = params[:consolidated_only] == '1'

      response.headers['Content-Type'] = 'text/plain'
      Dsars::Importer.new(ENV['DSARS_USERNAME'], ENV['DSARS_PASSWORD']).import(incident_number, since: since, consolidated_only: consolidated_only) do |message|
        puts message
        response.stream.write message
      end
    ensure
      response.stream.close
    end

    protected

    def add_breadcrumbs
      super
      breadcrumb "Import"
    end

  end
end

dsars/app/controllers/dsars/report_lines_controller.rb
class ReportLinesController < ApplicationController

  def lines
    @reports = Report.where(report_type: '5266', dro_number: params[:incident_id], scope: ['Consolidated', 'Chapter'])
    @lines = ReportLine.where(report_id: @reports, line_number: params[:line_number])
  end

end

dsars/app/controllers/dsars/reports_controller.rb
module Dsars
  class ReportsController < ApplicationController
    inherit_resources
    belongs_to :environment, finder: :find_by_slug!
    defaults finder: :find_by_report_number

    def index
      incident = params[:incident_id]
      @reports = end_of_association_chain.order{report_number.desc}.to_a
    end

    def show
      @incident = params[:incident_id]
      @report_num = params[:id]
      @report = end_of_association_chain.where{(report_number == my{@report_num})}.first
    end

    protected

    def add_breadcrumbs
      super
      if params[:action] != 'index'
        breadcrumb "Report #{params[:id]}", reports_path(parent, params[:id])
      end
    end

    def end_of_association_chain
      Report.where{(report_type == '5266')}.where{dro_number == my{parent.dr_number}}.consolidated
    end
  end
end

dsars/app/helpers/dsars/application_helper.rb
module Dsars
  module ApplicationHelper
  end
end

dsars/app/helpers/dsars/dosr_helper.rb
module Dsars
  module DosrHelper
    def sparkline_image_url data
      min, max = data.minmax
      delta = max-min
      min -= delta * 0.05
      max += delta * 0.05
      Gchart.sparkline  size: '300x25', data: data, use_ssl: true, 
                        min_value: min, max_value: max, 
                        bg: "00000000", 
                        line_colors: "6D6E70",
                        new_markers: "o,ED1B2E,0,-1:-1:1,5,1", 
                        custom: "chma=0,5,0,0"
    end

  end
end

dsars/app/helpers/dsars/reports_helper.rb
module Dsars
  module ReportsHelper
    def format val, type
      case type
      when 'currency'
        number_to_currency val, precision: 0
      else
        number_with_delimiter val
      end
    end

    def descr line
      @line_descriptions[line].first.name
    end

    def disabled_row
      safe_join [tag(:td, class: 'disabled'), tag(:td, class: 'disabled'), tag(:td, class: 'disabled'), tag(:td, class: 'disabled end-col')]
    end

    def finance_row line_number
      return disabled_row unless line_number
      line = line_for_num line_number
      desc = line_description line_number

      content_tag(:td, link_to(line.line_number, report_chart_path(parent, @report.report_number, line.line_number))) <<
      content_tag(:td, format(line.period, desc.format), class: "val") <<
      content_tag(:td, format(line.total, desc.format), class: "val") <<
      tag(:td, class: "end-col")
    end

    def line_description num
      @line_descriptions ||= Dsars::LineDescription.where{report_type=='5266'}.group_by(&:line_number)
      @line_descriptions[num].try :first
    end

    def line_for_num num
      @lines_by_number ||= @report.lines.order{line_number}.group_by(&:line_number)
      @lines_by_number[num].first
    end

    def finance_columns
      [
        ["Mass Care PSC21", "Class 2", "Class 3", "Class 4", "Class 6", "Total Client Casework", "Health Svcs Class 5",
          "Mental Health Class 5M", "Safe & Well", "DA/LG/CPS", "Recovery Planning & Asst.", "Total Deductions in CAS",
          "Total Relief Commitments", "OM/FSI/ID/Finance", "Log/DST/Staff", "Fund Raising", "Public Affairs", "Total Operation Commitments",
          "Value of In Kind Donations", "Temp Daily Rental Units", "Temp Monthly Rental Units", "Hotel/Motel Rent Dollars"],
        [nil, 83, 84, 85, 86, 87, 88, 89, nil, nil, 90, 91, 92, nil, nil, nil, nil, 93, nil, 94, 95, 96],
        [97, nil, nil, nil, nil, 98, 99, 100, 101, 102, 103, nil, 104, 105, 106, 107, 108, 109, 110, nil, nil, nil],
        [111, nil, nil, nil, nil, 112, 113, 114, 115, 116, 117, nil, 118, 119, 120, 121, 122, 123, nil, nil, nil, nil],
        (124..145).to_a
      ]
    end
  end
end

dsars/app/views/dsars/reports/index.html.haml
%h1 DSARS - #{parent.name}
-if current_ability.role? Roles::Dsars::IMPORT
  =link_to "Import DSARS Reports", input_path
%table.table
  %thead
    %tr
      %th Report Number
      %th COB Date
      %th View
      %th Actions
  %tbody
    - @reports.each do |rep|
      %tr
        %td=rep.report_number
        %td=rep.cob_date
        %td
          =link_to "5266", report_path(parent, rep.report_number)
          \|
          =link_to "DOSR", report_dosr_path(parent, rep.report_number)
        %td Re-Import Report

dsars/app/views/dsars/reports/list.html.haml
=form_tag url_for(action: :run_report), method: :post do
  %h3 Choose report:
  - @report_types.each do |type|
    %div
      =radio_button_tag 'report_type', type
      =label_tag "report_type_#{type.gsub ' ', '_'}", type
  %div
    =label_tag :dro_number
    =text_field_tag :dro_number

  %div
    =label_tag :dro_title
    =text_field_tag :dro_title

  %div
    =label_tag :cob_date
    =text_field_tag :cob_date
    "yyyy-mm-dd"

  %div
    =label_tag :message
    =text_area_tag :message

  =submit_tag 'Run Report'

dsars/app/views/dsars/reports/show.html.haml
%h1
  =@report.incident_name
  =@report.scope
  =@report.cob_date
%table.table.table-condensed.report-table.table-bordered
  %thead
    %tr
      %th Line
      %th Name
      %th Pd
      %th Ttl
      %th *
      %th Line
      %th Name
      %th Pd
      %th Ttl
      %th *
  %tbody
    - lines_in_first_col = 46
    - lines_in_first_page = 82
    - (1..lines_in_first_col).each do |line_first_idx|
      %tr
        - line = line_for_num line_first_idx
        - desc = line_description line_first_idx
        %td=link_to line.line_number, report_chart_path(parent, @report.report_number, line.line_number)
        %td=desc.name
        %td.val=format(line.period, desc.format)
        %td.val=format(line.total, desc.format)
        %td.end-col
        - line_second_idx = line_first_idx + lines_in_first_col
        - if line_second_idx <= lines_in_first_page
          - line = line_for_num line_second_idx
          - desc = line_description line_second_idx
          %td=link_to line.line_number, report_chart_path(parent, @report.report_number, line.line_number)
          %td=desc.name
          %td.val{class: desc.has_period || 'disabled'}=format(line.period, desc.format)
          %td.val{class: desc.has_total || 'disabled'}=format(line.total, desc.format)
          %td
- if current_ability.role? Roles::Dsars::FINANCIALS
  %table.table.table-condensed.report-table.table-bordered.finance-table
    %thead
      %tr
        %td(colspan="2")
        %th(colspan="3") CLS
        %td.end-col
        %th(colspan="3") Logistics and Technology
        %td.end-col
        %th(colspan="3") Staff Services
        %td.end-col
        %th(colspan="3") Total
      %tr
        %th(colspan="2") Data Elements
        %th #
        %th Period
        %th To Date
        %th.end-col *
        %th #
        %th Period
        %th To Date
        %th.end-col *
        %th #
        %th Period
        %th To Date
        %th.end-col *
        %th #
        %th Period
        %th To Date
    %tbody
      - finance_columns.first.each_index do |idx|
        %tr
          %td
          %td=finance_columns[0][idx]
          =finance_row finance_columns[1][idx]
          =finance_row finance_columns[2][idx]
          =finance_row finance_columns[3][idx]
          =finance_row finance_columns[4][idx]