sitreps/config/routes.rb
Sitreps::Engine.routes.draw do
  scope ':environment_id', as: :environment do
    resource :sitrep_config, controller: 'config', as: :sitrep_config#, only: [:edit, :update, :create]
    resources :sitreps, path_names: {new: 'submit'} do
      collection do
        get :print
        get :submitted
      end
    end
  end
end

sitreps/app/models/sitreps/prompt.rb
module Sitreps
  class Prompt < ActiveRecord::Base
    belongs_to :config
    validates :title, presence: true
  end
end

sitreps/app/models/sitreps/response.rb
module Sitreps
  class Response < ActiveRecord::Base
    belongs_to :sitrep
    validates :title, :ordinal, :response, presence: true
  end
end

sitreps/app/models/sitreps/sitrep.rb
module Sitreps
  class Sitrep < ActiveRecord::Base
    belongs_to :environment
    belongs_to :creator
    has_many :responses, ->{ order{ordinal} }

    accepts_nested_attributes_for :responses, update_only: true

    validates :date, :activity, :submitter_name, :submitter_title, :territory, presence: true
    validates_associated :responses

    def self.for_environment env
      where{environment_id == env}
    end

    def self.for_date date_val
      where{date == date_val}
    end

  end
end

sitreps/app/models/sitreps/sitrep_config.rb
module Sitreps
  class SitrepConfig < ActiveRecord::Base
    belongs_to :environment
    has_many :prompts, -> { order(:ordinal) }
    accepts_nested_attributes_for :prompts, allow_destroy: true

    validates :environment, presence: true

    def self.for_environment env
      find_by environment_id: env
    end

    def self.find_or_initialize_for_environment env
      find_or_initialize_by environment_id: env.id
    end
  end
end

sitreps/app/models/sitreps/sitreps.rb
module Sitreps
  module Sitreps
    def self.table_name_prefix
      'sitreps_sitreps_'
    end
  end
end

sitreps/app/controllers/sitreps/application_controller.rb
module Sitreps
  class ApplicationController < ::ApplicationController
    self.component_name = :sitreps
    before_filter :require_enabled_component!
    
    def add_breadcrumbs
      breadcrumb 'Sitreps', collection_path
    end
  end
end

sitreps/app/controllers/sitreps/config_controller.rb
require_dependency "sitreps/application_controller"

module Sitreps
  class ConfigController < ApplicationController
    inherit_resources
    defaults resource_class: SitrepConfig, singleton: true, route_prefix: nil, route_instance_name: :sitrep_config, instance_name: :sitrep_config
    config[:request_name] = :sitrep_config
    belongs_to :environment, finder: :find_by_slug!

    actions :all, except: [:index, :show]

    before_filter :authorize_resource

    private

    def authorize_resource
      authorize!(Roles::Sitreps::ADMIN)
    end

    def add_breadcrumbs
      breadcrumb "Config", edit_resource_path
    end

    def smart_collection_url
      environment_sitreps_path
    end

    def resource
      @sitrep_config ||= SitrepConfig.find_or_initialize_for_environment parent
    end

    def build_resource
      @sitrep_config ||= begin
        res = SitrepConfig.find_or_initialize_for_environment parent
        res.send :attributes=, *resource_params
        res.prompts.each_with_index do |prompt, idx|
          prompt.ordinal = idx
        end
        res
      end
    end

    def permitted_params
      params.permit(sitrep_config: [:allow_unauthenticated_submit, prompts_attributes: [:id, :title, :required, :ordinal, :_destroy]])
    end
  end
end

sitreps/app/controllers/sitreps/sitreps_controller.rb
require_dependency "sitreps/application_controller"

module Sitreps
  class SitrepsController < ApplicationController
    inherit_resources
    defaults route_prefix: nil
    respond_to :html, :pdf
    belongs_to :environment, finder: :find_by_slug!
    config[:request_name] = :sitrep

    custom_actions collection: [:print, :submitted]
    actions :all, except: :show

    skip_before_filter :authenticate_user!, only: [:new, :create, :submitted]
    before_filter :check_anonymous_submit_or_authenticate!, only: [:new, :create]

    responders :pdf

    has_scope :for_date, default: Date.current.to_s, only: :print

    def create
      create! { current_user ? smart_collection_url : submitted_resources_path }
    end

    protected

    def add_breadcrumbs
      super
      if params[:action] != 'index'
        breadcrumb params[:action].titleize
      end
    end

    def end_of_association_chain
      resource_class.for_environment parent
    end

    helper_method :sitrep_config
    def sitrep_config
      @sitrep_config ||= SitrepConfig.for_environment parent
    end

    def build_resource_params
      [params.fetch(:sitrep, {}).permit(:date, :activity, :submitter_name, :submitter_title, :territory, responses_attributes: [:id, :title, :response, :ordinal]).merge(:creator_id => current_user.try(:id))]
    end

    def build_resource
      @sitrep ||= super.tap { |sitrep|
        sitrep.date ||= Date.current
        sitrep.submitter_name ||= (current_user && current_user.full_name)
        existing = sitrep.responses.map(&:title)
        sitrep_config.prompts.each do |p|
          sitrep.responses.build title: p.title unless existing.include? p.title
        end
      }
    end

    def check_anonymous_submit_or_authenticate!
      authenticate_user! unless sitrep_config && sitrep_config.allow_unauthenticated_submit
    end

    def collection
      @coll ||= apply_scopes(super)
    end
  end
end

sitreps/app/helpers/sitreps/application_helper.rb
module Sitreps
  module ApplicationHelper
  end
end

sitreps/app/helpers/sitreps/config_helper.rb
module Sitreps
  module ConfigHelper
  end
end

sitreps/app/helpers/sitreps/sitreps_helper.rb
module Sitreps
  module SitrepsHelper
  end
end

sitreps/app/views/sitreps/config/_prompt_fields.html.haml
- f.object.ordinal ||= 100000
.nested-fields
  = f.inputs do
    =f.hidden_field :ordinal
    =f.input :title
    =f.input :required, as: :boolean
  .links
    = link_to_remove_association "remove prompt", f

sitreps/app/views/sitreps/config/edit.html.haml
=semantic_form_for resource, url: environment_sitrep_config_path(parent), builder: FormtasticBootstrap::FormBuilder, class: 'form' do |f|
  =f.input :allow_unauthenticated_submit
  .prompts
    - idx = 0
    =f.fields_for :prompts do |prompt|
      =render 'prompt_fields', f: prompt, ordinal: idx
    =link_to_add_association 'add prompt', f, :prompts
  =f.actions

sitreps/app/views/sitreps/sitreps/_form.html.haml
=semantic_form_for [parent, resource], builder: FormtasticBootstrap::FormBuilder do |f|
  =f.input :date
  .row
    .col-sm-6
      =f.input :activity
    .col-sm-6
      =f.input :territory, collection: parent.territories.map(&:name)
  .row
    .col-sm-6
      =f.input :submitter_name
    .col-sm-6
      =f.input :submitter_title
  - idx = 0
  =f.fields_for :responses do |resp|
    =resp.hidden_field :id
    =resp.hidden_field :title
    =resp.hidden_field :ordinal, {value: idx}
    =resp.input :response, as: :text, input_html: {rows: 5}, label: resp.object.title
    - idx += 1

  =f.action :submit, label: 'Submit SitRep', button_html: {class: 'btn btn-primary'}

sitreps/app/views/sitreps/sitreps/index.html.haml
%h1
  =parent.name
  Sitreps
  -if sitrep_config
    =link_to "Submit Situation Report", new_resource_path(parent), class: "btn btn-primary"
  -if role?(Roles::Sitreps::ADMIN)
    =link_to "Configure", edit_environment_sitrep_config_path(parent), class: 'btn'
%table.table.table-condensed
  %thead
    %tr
      %th Date
      %th Territory
      %th Activity
      %th Submitter
      %th Submitted At
      %th Actions
  %tbody
    - collection.each do |resource|
      %tr
        %td=resource.date
        %td=resource.territory
        %td=resource.activity
        %td=resource.submitter_name
        %td=resource.created_at
        %td
          =link_to 'Show', resource_path(resource), class: "btn btn-primary btn-xs"
          =link_to 'Edit', edit_resource_path(resource), class: "btn btn-primary btn-xs"

sitreps/app/views/sitreps/sitreps/print.html.haml
.hidden-print
  .well
    Date:
    =form_tag '', method: :get do
      =date_field_tag :for_date, current_scopes[:for_date], class: 'form_control'
      =submit_tag 'Show', class: 'btn btn-primary'
.sitrep-pages
  - collection.each do |resource|
    .sitrep-page
      .banner
        %h1
          =parent.name
          Sitreps
      .header
        %table.table.header-table
          %tr
            %td
              %h4 Date
              = resource.date
            %td
              %h4 Activity
              = resource.activity
            %td
              %h4 Territory
              = resource.territory
            %td
              %h4 Submitted By
              = resource.submitter_name
      .clearfix(style="clear: both")
      .body.clearfix
        - resource.responses.each do |resp|
          %hr
          %h4=resp.title
          =simple_format resp.response
      %hr.end-page

sitreps/app/views/sitreps/sitreps/show.html.haml
=render resource

sitreps/app/views/sitreps/sitreps/submitted.html.haml
%h2.text-success
  Your sitrep has been successfully submitted.