iap/config/routes.rb
Iap::Engine.routes.draw do
  scope ':environment_id', as: :environment do

    resources :plans, path: 'iap' do
      collection do
        resources :recipients, except: :show do
          collection do
            get :addresses
          end
        end
      end

      resource :distribution, only: [:new, :create]
      resource :approval, only: [:new, :create, :destroy]
      resources :planning_worksheets
      resources :work_assignments do
        post :duplicate, on: :member
        collection do
          get :print
          get :upload
          post :perform_upload
        end
      end

      resource :work_location_verification, controller: :work_location_verification

      resources :attachments, controller: :plan_attachments do
        collection do
          get 'new/upload', action: 'new_upload', as: :new_upload
          scope 'new/drive', controller: 'drive_list' do
            get :switch_user
            get '(:folder_id)', action: 'index', as: :list_drive
            get ':folder_id/assemble', to: 'drive_assemble#new', as: :new_drive
            post ':folder_id/assemble', to: 'drive_assemble#create', as: :create_drive
          end
          get 'new/:source', action: 'new_render', as: :new_render
        end
      end

      collection do
        resource :template, controller: :template do
          get 'new/(:folder_id)', action: 'new', as: :list_drive
          post 'switch_user'
        end
      end

    end
  end

  get "auth/#{Iap::Engine::IAP_OMNIAUTH_NAME}/callback", to: "drive_list#callback"
end

iap/app/models/iap/environment_additions.rb
module Iap
  module EnvironmentAdditions
    extend ActiveSupport::Concern

    included do
      has_many :plans, class_name: 'Iap::Plan'
      has_many :recipients, class_name: 'Iap::Recipient'
    end
  end
end

iap/app/models/iap/iap.rb
module Iap
  module Iap
    def self.table_name_prefix
      'iap_iap_'
    end
  end
end

iap/app/models/iap/plan.rb
module Iap
  class Plan < ActiveRecord::Base
    belongs_to :environment
    validates :number, presence: true, uniqueness: {scope: :environment_id}
    validates :approver_name, :approver_title, presence: {if: :approved?}

    has_many :plan_attachments, dependent: :destroy
    has_many :planning_worksheets, dependent: :destroy
    has_many :work_assignments, dependent: :destroy

    assignable_values_for :status do
      %w(draft approved)
    end

    def self.for_environment env
      where{environment_id == env}
    end

    def self.draft
      where{status == 'draft'}
    end

    def self.approved
      where{status == 'approved'}
    end

    def self.upcoming now=Time.zone.now
      approved.where{period_start >= now}
    end

    def self.current now=Time.zone.now
      approved.where{(period_start <= now) & (period_end > now)}
    end

    def self.past now=Time.zone.now
      approved.where{period_end < now}
    end

    def to_param
      number
    end

    def to_breadcrumb
      "##{number}"
    end

    def approved?
      status == 'approved'
    end
  end
end

iap/app/models/iap/plan_attachment.rb
module Iap
  class PlanAttachment < ActiveRecord::Base
    belongs_to :plan
    has_attached_file :file
    do_not_validate_attachment_file_type :file

    #validates :file, presence: true

    assignable_values_for :audience do
      %w(all internal leadership)
    end

    assignable_values_for :attachment_type do
      %w(plan sitrep other)
    end
  end
end

iap/app/models/iap/planning_worksheet.rb
module Iap
  class PlanningWorksheet < ActiveRecord::Base
    belongs_to :plan
    has_many :planning_worksheet_lines
    accepts_nested_attributes_for :planning_worksheet_lines, allow_destroy: true
  end
end

iap/app/models/iap/planning_worksheet_line.rb
module Iap
  class PlanningWorksheetLine < ActiveRecord::Base
    belongs_to :planning_worksheet
    has_many :planning_worksheet_resources
    accepts_nested_attributes_for :planning_worksheet_resources, allow_destroy: true

    def resource_line ordinal
      planning_worksheet_resources.detect{|res| res.ordinal == ordinal}
    end
  end
end

iap/app/models/iap/planning_worksheet_resource.rb
module Iap
  class PlanningWorksheetResource < ActiveRecord::Base
    belongs_to :planning_worksheet_line
  end
end

iap/app/models/iap/recipient.rb
module Iap
  class Recipient < ActiveRecord::Base
    belongs_to :environment

    assignable_values_for :recipient_type do
      %w(internal external leadership)
    end
  end
end

iap/app/models/iap/subscription.rb
module Iap
  class Subscription < ActiveRecord::Base
    belongs_to :environment
    belongs_to :user
  end
end

iap/app/models/iap/work_assignment.rb
module Iap
  class WorkAssignment < ActiveRecord::Base
    belongs_to :plan
    has_many :work_assignment_lines
    accepts_nested_attributes_for :work_assignment_lines, allow_destroy: true

    def duplicate
      new_ass = self.dup
      work_assignment_lines.each do |line|
        new_ass.work_assignment_lines << line.dup
      end
      new_ass
    end
  end
end

iap/app/models/iap/work_assignment_line.rb
module Iap
  class WorkAssignmentLine < ActiveRecord::Base
    belongs_to :work_assignment
    default_scope ->{order{ordinal}}
  end
end

iap/app/models/iap/work_location_verification.rb
require_dependency Iap::Engine.root.join('lib', 'flat_group_by').to_s

module Iap
  class WorkLocationVerification
    def initialize plan
      @plan = plan
      @environment = plan.environment
    end

    attr_reader :plan, :environment

    def mismatched_staff
      @mismatched_staff ||= calculate_mismatched_staff
    end

    def calculate_mismatched_staff
      staff_by_name = assigned_staff.flat_group_by(&:name)
      lines_by_name = assignment_lines.flat_group_by(&:leader)

      unmatched = []
      mismatched = []
      lines_by_name.each do |name, assignment|
        staff = staff_by_name[name]
        unless staff
          unmatched << assignment
          next
        end

        record = Record.new(staff, staff.work_location, assignment.work_assignment.work_location, assignment)
        mismatched << record if record.mismatched?
      end

      mismatched
    end

    def assigned_staff
      @assigned_staff ||= environment.assigned_staff.to_a
    end

    def assignment_lines
      @assignment_lines ||= WorkAssignmentLine.joins{work_assignment}.where{work_assignment.plan_id == my{plan}}.preload{work_assignment}.to_a
    end

    Record = Struct.new(:person, :old_location, :new_location, :work_assignment) do
      def mismatched?
        old_location != new_location
      end
    end
  end
end

iap/app/controllers/iap/application_controller.rb
module Iap
  class ApplicationController < ::ApplicationController
    self.component_name = :iap
    before_filter :require_enabled_component!
    
    def add_breadcrumbs
      breadcrumb "IAP", environment_plans_path(parent)
    end

    protected

    def authorize_producer!
      authorize! Roles::Iap::PRODUCER
    end

    def authorize_approver!
      authorize! Roles::Iap::APPROVER
    end

    def authorize_iap_role!
      authorize! [Roles::Iap::APPROVER, Roles::Iap::PRODUCER]
    end
  end
end

iap/app/controllers/iap/approvals_controller.rb
module Iap
  class ApprovalsController < ApplicationController
    inherit_resources
    defaults route_prefix: nil, finder: :find_by_number!, collection_name: 'plans', route_instance_name: :plan_approval
    config[:request_name] = :plan
    belongs_to :environment, finder: :find_by_slug!
    prepend_before_filter :set_id

    actions :new, :create, :destroy, :update

    before_filter :authorize_approver!

    def destroy
      resource.approver_name = resource.approver_title = resource.approved_at = nil
      resource.status = 'draft'
      update!
    end

    protected

    def set_id
      params[:id] = params.delete :plan_id
    end

    def build_resource
      @plan ||= resource.tap do |plan|
        plan.send :attributes=, *resource_params
        plan.approver_name = current_user.full_name unless plan.approver_name.present?
        plan.approved_at = Time.current
        plan.status = 'approved'
      end
    end

    def build_resource_params
      [params.fetch(:plan, {}).permit(:approver_name, :approver_title)]
    end
  end
end

iap/app/controllers/iap/distributions_controller.rb
module Iap
  class DistributionsController < ApplicationController
    inherit_resources
    defaults route_prefix: nil, finder: :find_by_number!, collection_name: 'plans', route_instance_name: :plan_approval
    config[:request_name] = :plan
    belongs_to :environment, finder: :find_by_slug!
    prepend_before_filter :set_id

    actions :new, :create, :destroy, :update

    before_filter :authorize_approver!

    def destroy
      resource.approver_name = resource.approver_title = resource.approved_at = nil
      resource.status = 'draft'
      update!
    end

    protected

    def set_id
      params[:id] = params.delete :plan_id
    end

    def build_resource
      @plan ||= resource.tap do |plan|
        plan.send :attributes=, *resource_params
        plan.approver_name = current_user.full_name unless plan.approver_name.present?
        plan.approved_at = Time.current
        plan.status = 'approved'
      end
    end

    def build_resource_params
      [params.fetch(:plan, {}).permit(:approver_name, :approver_title)]
    end
  end
end

iap/app/controllers/iap/drive_assemble_controller.rb
module Iap
  class DriveAssembleController < ApplicationController
    include GoogleController
    before_filter :authenticate_oauth!
    helper DriveListHelper
    helper PlanAttachmentsHelper
    inherit_resources
    defaults resource_class: PlanAttachment, route_prefix: nil, collection_name: 'plan_attachments'
    belongs_to :environment, finder: :find_by_slug!
    belongs_to :plan, finder: :find_by_number!

    before_filter :require_draft_plan
    before_filter :authorize_producer!

    def create
      build_resource
      resource.valid?
      if resource.errors.none? {|k, errors| k != :file}
        if is_regular_file?
          make_pdf [file]
        else
          make_pdf files
        end
      else
        super
      end
    end

    protected

    def require_draft_plan
      if parent.approved?
        flash[:error] = "This IAP is approved and cannot be edited."
        redirect_to parent_path
      end
    end

    def make_pdf files
      DriveAssembler.new(drive, files).assemble do |file|
        filename = "#{build_resource.title}.pdf"
        build_resource.file = file
        build_resource.file.instance_write(:file_name, filename)
        create! { environment_plan_path(*association_chain) }
      end
    end

    helper_method :files, :file, :is_regular_file?

    def files
      @files ||= begin
        items = drive.list_folder(params[:folder_id])['items']
        items.sort_by!{|f| f['title']}
        items.select{|f| f['mimeType'] != "application/vnd.google-apps.folder" }
      end
    end

    def file
      @file ||= drive.get_file params[:folder_id]
    end

    def is_regular_file?
      file['mimeType'] != "application/vnd.google-apps.folder"
    end

    def build_resource
      @plan_attachment ||= super.tap do |att|
        att.title ||= file['title']
      end
    end

    def build_resource_params
      [params.fetch(:plan_attachment, {}).permit(:title, :audience, :attachment_type)]
    end
  end
end

iap/app/controllers/iap/drive_list_controller.rb
module Iap
  class DriveListController < ApplicationController
    include GoogleController

    before_filter :authenticate_oauth!
    skip_before_filter :add_breadcrumbs!, except: :index
    before_filter :require_draft_plan, only: :index
    before_filter :authorize_producer!, only: :index

    MIME_FOLDER = "application/vnd.google-apps.folder"

    def index
      params[:folder_id] ||= 'root'

      @folder = drive.get_file params[:folder_id]
      items = drive.list_folder(params[:folder_id])['items']
      items.sort_by!{|f| f['title']}

      @folders = items.select{|f| f['mimeType'] == MIME_FOLDER }
      @files = items.reject{|f| f['mimeType'] == MIME_FOLDER }
    end

    protected

    def require_draft_plan
      if parent.approved?
        flash[:error] = "This IAP is approved and cannot be edited."
        redirect_to parent_path
      end
    end

    helper_method :environment, :parent
    def environment
      @environment ||= Environment.find_by_slug! params[:environment_id]
    end

    def parent
      @parent ||= environment.plans.find_by_number! params[:plan_id]
    end

    def parent_path
      environment_plan_path(environment, parent)
    end

    helper_method :list_folder_path, :assemble_path, :parent_folder_path
    def list_folder_path(folder_id)
      url_for folder_id: folder_id
    end

    def assemble_path(item_id=nil)
      item_id ||= params[:folder_id]
      url_for folder_id: item_id, controller: 'drive_assemble', action: 'new'
    end

    def parent_folder_path
      url_for folder_id: parent_folder_id
    end

    def parent_folder_id
      (ref = @folder['parents'].first ) && ref['id']
    end

    def add_breadcrumbs
      breadcrumb "IAP", environment_plans_path(environment)
      breadcrumb parent.to_breadcrumb, environment_plan_path(environment, parent)
      breadcrumb "New Attachment"
    end

    helper_method :is_valid
    def is_valid(f)
      f['mimeType'] == 'application/pdf' ||
      (f['exportLinks'] && f['exportLinks']['application/pdf'])
    end

    helper_method :all_valid
    def all_valid
      @files.all?{|f| is_valid(f)}
    end

    def auth_hash
      request.env['omniauth.auth']
    end

    def drive
      @drive ||= Drive.new(api_client)
    end
  end
end

iap/app/controllers/iap/plan_attachments_controller.rb
module Iap
  class PlanAttachmentsController < ApplicationController
    inherit_resources
    defaults resource_class: PlanAttachment, route_prefix: nil
    belongs_to :environment, finder: :find_by_slug!
    belongs_to :plan, finder: :find_by_number!
    before_filter :require_draft_plan
    before_filter :authorize_producer!

    def new_upload
      new!
    end

    protected

    def require_draft_plan
      if parent.approved?
        flash[:error] = "This IAP is approved and cannot be edited."
        redirect_to parent_path
      end
    end

    def add_breadcrumbs
      super
      breadcrumb parent.to_breadcrumb, parent_path
      breadcrumb "Attachment"
    end

    def build_resource_params
      [params.fetch(:plan_attachment, {}).permit(:title, :audience, :attachment_type, :file)]
    end
  end
end

iap/app/controllers/iap/planning_worksheets_controller.rb
require_dependency "iap/application_controller"

module Iap
  class PlanningWorksheetsController < ApplicationController
    inherit_resources
    belongs_to :environment, finder: :find_by_slug!
    belongs_to :plan, finder: :find_by_number!
    defaults route_prefix: nil
    actions :all, except: :show

    def smart_resource_url
      edit_resource_path
    end

    protected

    def add_breadcrumbs
      super
      breadcrumb parent.to_breadcrumb, parent_path
      breadcrumb "Planning Worksheets", (params[:id] && collection_path)
      breadcrumb (resource.activity || "New Worksheet") if params[:id]
    end

    def build_resource_params
      [params.fetch(:planning_worksheet, {}).permit(:district, :group, :activity, :prepared_by_name, :prepared_by_title, :completed,
          planning_worksheet_lines_attributes: [:_destroy, :id, :work_assignment, :location,
            planning_worksheet_resources_attributes: [:ordinal, :requested, :have, :need, :resource, :id]])]
    end
  end
end

iap/app/controllers/iap/plans_controller.rb
module Iap
  class PlansController < ApplicationController
    inherit_resources
    defaults route_prefix: nil, finder: :find_by_number!
    config[:request_name] = :plan
    belongs_to :environment, finder: :find_by_slug!

    before_filter :require_draft_plan, only: [:edit, :update]
    before_filter :authorize_producer!, except: [:index, :show]

    protected

    def previous_plan
      @previous_plan ||= collection.order{number.desc}.first
    end

    def require_draft_plan
      if resource.approved?
        flash[:error] = "This IAP is approved and cannot be edited."
        redirect_to resource_path
      end
    end

    helper_method :editable?
    def editable?
      !resource.approved?
    end

    def add_breadcrumbs
      super
      case params[:action]
      when 'index' then
      when 'new', 'create' then breadcrumb params[:action].titleize, url_for
      else
        breadcrumb resource.to_breadcrumb
      end
    end

    def build_resource
      super.tap{|res|
        res.number ||= next_plan_number
        res.status ||= 'draft'

        if previous_plan
          previous_plan.work_assignments.each{|wa| 
            new_wa = wa.duplicate
            new_wa.created_at = nil
            new_wa.prepared_by_name = nil
            new_wa.prepared_by_title = nil
            res.work_assignments << new_wa
          }
          res.period_start = previous_plan.period_end
          res.period_end = res.period_start + (previous_plan.period_end - previous_plan.period_start)
        end
      }
    end

    def next_plan_number
      (end_of_association_chain.maximum(:number) || 0) + 1
    end

    def build_resource_params
      [params.fetch(:plan, {}).permit(:number, :period_start, :period_end, :approver_name, :approver_title, :status)]
    end
  end
end

iap/app/views/iap/work_assignments/_form.html.haml
=semantic_form_for [parent, resource], url: (resource.persisted? ? resource_path(resource) : collection_path), builder: FormtasticBootstrap::FormBuilder, class: 'print-table' do |f|
  %h3.center ICS 204 Work Assignment
  %table.table.table-bordered.print-table
    %tr
      %td.table-header-cell
        %strong 1. Incident Name
        %br
        =f.object.plan.environment.name
      %td.table-header-cell
        .inline-block
          %strong 2. Op. Period
        .inline-block.ops-period
          From:
          =f.object.plan.period_start.try(:to_s, :date_time)
          %br
          To:
          =f.object.plan.period_end.try(:to_s, :date_time)
      %td(rowspan="2")
        %strong 3.
        %br
        =f.label :group, 'Group:'
        =f.text_field :group
        %br
        =f.label :activity, 'Activity:'
        =f.text_field :activity
        %br
        =f.label :district, 'District:'
        =f.text_field :district
        .hidden-print
          =f.label :work_location, 'Work Location:'
          =f.select :work_location, work_locations(parent.environment), include_blank: true
    %tr
      %td.table-nested-container(colspan="2" style="border-top: 0")
        %table.table.table-nested.personnel-table
          %tr
            %th.form-header-cell 4. Personnel
            %th.form-header-cell Name
            %th.form-header-cell Contact Number
          %tr.name-autofill
            %td.form-header-cell.personnel-label Assistant Director:
            %td.form-cell=f.text_field :section_chief_name, placeholder: "Name", class: 'autofill-name-field'
            %td.form-cell=f.text_field :section_chief_phone, placeholder: '###-###-####', class: 'autofill-phone-field'
          %tr.name-autofill
            %td.form-header-cell.personnel-label Manager:
            %td.form-cell=f.text_field :activity_manager_name, placeholder: "Name", class: 'autofill-name-field'
            %td.form-cell=f.text_field :activity_manager_phone, placeholder: '###-###-####', class: 'autofill-phone-field'
          %tr.name-autofill
            %td.form-header-cell.personnel-label Supervisor:
            %td.form-cell=f.text_field :supervisor_name, placeholder: "Name", class: 'autofill-name-field'
            %td.form-cell=f.text_field :supervisor_phone, placeholder: '###-###-####', class: 'autofill-phone-field'
    %tr
      %td.table-nested-container(colspan="3")
        %table.table.table-nested.table-bordered.table-condensed.assignments-table
          %thead
            %tr
              %th(colspan="2") 5. Resources Assigned:
              %td.num-persons-cell(rowspan="2")
                %small 
                  \#
                  %br
                  Per
                  %br
                  sons
              %td.contact-number-cell(rowspan="2") Contact Number
              %td.reporting-location-cell(rowspan="2") Reporting Location
            %tr
              %td.resource-identifier-cell Resource Identifier
              %td.leader-cell Leader
          %tbody.worksheet-lines
            =f.fields_for :work_assignment_lines , include_id: false do |f|
              =render 'work_assignment_line_fields', f: f, editable: editable
          - if editable
            %tfoot.hidden-print
              %td(colspan="5")
                =link_to_add_association 'add line', f, :work_assignment_lines, data: {association_insertion_method: "append", association_insertion_node: "tbody.worksheet-lines"}, class: 'btn btn-primary'
    %tr
      %td.area-cell.keep-padding(colspan="3")
        %strong 6. Work Assignments:
        %br
        =f.text_area :work_assignments
    %tr
      %td.area-cell.keep-padding(colspan="3")
        %strong 7. Special Instructions
        %br
        =f.text_area :special_instructions
    %tr
      %td(colspan="3")
        %strong 8. Communications
        %br
    %tr
      %td(colspan="3")
        %strong 9. Prepared by:
        =f.text_field :prepared_by_name
        %strong Title:
        =f.text_field :prepared_by_title
        Date/Time:
        =f.object.updated_at.try(:to_s, :date_time)

  -if editable
    .hidden-print
      =f.action :submit, button_html: {class: 'btn btn-primary'}, label: 'Save Work Assignment'

:javascript
  window.workAssignmentController = new WorkAssignmentController(#{person_datasource_url.to_json}, #{current_environment.dr_number.to_json});

iap/app/views/iap/work_assignments/_work_assignment_line_fields.html.haml
%tr.nested-fields.name-autofill
  %td.form-cell.resource-identifier-cell=f.text_field :resource_identifier, placeholder: "Name"
  %td.form-cell.leader-cell=f.text_field :leader, placeholder: "Leader Name", class: 'autofill-name-field'
  %td.form-cell.num-persons-cell=f.text_field :num_persons, placeholder: "#"
  %td.form-cell.contact-cell=f.text_field :contact, placeholder: '###-###-####', class: 'autofill-phone-field'
  %td.form-cell.reporting-location-cell=f.text_field :reporting_location, placeholder: "Address and Time"
  -if editable
    %td.form-header-cell.hidden-print
      =link_to_remove_association 'Remove', f, class: 'text-danger'
      =f.hidden_field :ordinal
      =f.hidden_field :id
    %td.form-header-cell.hidden-print.drag-cell Reorder

iap/app/views/iap/work_assignments/edit.html.haml
.work-assignment-page
  =render 'form'

iap/app/views/iap/work_assignments/index.html.haml
%table.table.table-condensed
  %tr
    %th District
    %th Group
    %th Activity
    %th Prepared By
    %th Actions
  - collection.each do |resource|
    %tr{class: resource.prepared_by_name.present? && 'success'}
      %td=resource.district
      %td=resource.group
      %td=resource.activity
      %td
        =resource.prepared_by_name
        =resource.prepared_by_title
      %td
        =link_to "Edit", edit_resource_path(resource)
        =link_to "Duplicate", duplicate_resource_path(resource), method: :post, data: {confirm: 'Really Duplicate?'}
        =link_to "Delete", resource_path(resource), method: :delete, data: {confirm: 'Really Destroy?'}
=link_to "Create 204", new_resource_path(), class: 'btn btn-primary'
=link_to "Print all 204s", print_resources_path, class: 'btn btn-default'

iap/app/views/iap/work_assignments/new.html.erb
<%= render 'form' %>

iap/app/views/iap/work_assignments/print.html.haml
.hidden-print
  .well
    =link_to 'Download PDF', format: :pdf
    \|
    =link_to 'Upload to Drive', upload_resources_path
.work-assignment-pages
  - collection.each do |form204|
    .work-assignment-page
      =render 'form', resource: form204, editable: false

iap/app/views/iap/work_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plan:</strong>
  <%= @work_assignment.plan %>
</p>

<p>
  <strong>Group:</strong>
  <%= @work_assignment.group %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @work_assignment.activity %>
</p>

<p>
  <strong>District:</strong>
  <%= @work_assignment.district %>
</p>

<p>
  <strong>Section chief name:</strong>
  <%= @work_assignment.section_chief_name %>
</p>

<p>
  <strong>Section chief phone:</strong>
  <%= @work_assignment.section_chief_phone %>
</p>

<p>
  <strong>Activity manager name:</strong>
  <%= @work_assignment.activity_manager_name %>
</p>

<p>
  <strong>Activity manager phone:</strong>
  <%= @work_assignment.activity_manager_phone %>
</p>

<p>
  <strong>Supervisor name:</strong>
  <%= @work_assignment.supervisor_name %>
</p>

<p>
  <strong>Supervisor phone:</strong>
  <%= @work_assignment.supervisor_phone %>
</p>

<p>
  <strong>Work assignments:</strong>
  <%= @work_assignment.work_assignments %>
</p>

<p>
  <strong>Special instructions:</strong>
  <%= @work_assignment.special_instructions %>
</p>

<p>
  <strong>Prepared by name:</strong>
  <%= @work_assignment.prepared_by_name %>
</p>

<p>
  <strong>Prepared by title:</strong>
  <%= @work_assignment.prepared_by_title %>
</p>

<p>
  <strong>Prepared at:</strong>
  <%= @work_assignment.prepared_at %>
</p>

<%= link_to 'Edit', edit_work_assignment_path(@work_assignment) %> |
<%= link_to 'Back', work_assignments_path %>

iap/app/views/iap/work_assignments/upload.html.haml
:javascript
  window.driveUploadController = new DriveUploadController(#{ENV['GOOGLE_BROWSER_KEY'].to_json}, #{access_token.to_json});
  function onApiLoad() {
    gapi.load('picker', {'callback': onPickerLoad})
  }
  function onPickerLoad() {
    window.driveUploadController.start()
  }

=javascript_include_tag 'https://apis.google.com/js/api.js?onload=onApiLoad'

=form_tag perform_upload_resources_path, method: :post, class: 'folder-form' do
  =hidden_field_tag :parent_folder